services:
  - type: web
    name: autolc-web
    env: node
    plan: free
    rootDir: .
    buildCommand: npm run build && cd server && npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /
